import 'package:app_android/models/alternative_product.dart';

class AlternativesService {
  static final List<AlternativeProduct> products = [
    AlternativeProduct(
      id: 1,
      name: 'Spéculoos au lait végétal',
      brand: 'Aux Caprices de Jess',
      category: 'Produits laitiers',
      barcode: '2000000025586',
      availability: 'Supermarches',
      benefits: ['Sans lactose'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/200/000/002/5586/front_fr.4.400.jpg',
      emoji: '🍫',
    ),
    AlternativeProduct(
      id: 2,
      name: 'Maïs doux',
      brand: 'Auchan Bio',
      category: 'Produits généraux',
      barcode: '3596710479955',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/359/671/047/9955/front_fr.68.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 3,
      name: 'Torsades bio maïs riz',
      brand: 'La Fourche',
      category: 'Pains & Pâtes',
      barcode: '3760324841174',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/376/032/484/1174/front_fr.22.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 4,
      name: 'Céréales bio fruits secs et graines No Gluten',
      brand: 'Carrefour',
      category: 'Pains & Pâtes',
      barcode: '3560070967728',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/356/007/096/7728/front_fr.40.400.jpg',
      emoji: '🍎',
    ),
    AlternativeProduct(
      id: 5,
      name: 'Petits pains de maïs Sans gluten',
      brand: 'Lidl',
      category: 'Pains & Pâtes',
      barcode: '05885282',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/000/000/588/5282/front_fr.3.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 6,
      name: 'Pois Chiches Au Naturel',
      brand: 'Karine & Jeff, Le bonheur est dans le pot',
      category: 'Pains & Pâtes',
      barcode: '3760052231421',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/376/005/223/1421/front_fr.12.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 7,
      name: 'Maïs doux',
      brand: 'U',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3256225039449',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/325/622/503/9449/front_en.11.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 8,
      name: 'Petits pois extra-fins au naturel',
      brand: 'Karine & Jeff, Le bonheur est dans le pot',
      category: 'Pains & Pâtes',
      barcode: '3760052230233',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/376/005/223/0233/front_fr.5.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 9,
      name: 'Maïs',
      brand: 'Auchan',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3596710488988',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/359/671/048/8988/front_fr.42.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 10,
      name: 'Céréale infantile Riz et Carottes Prémibio',
      brand: 'LOU BIO, Prémibio, Prémilait',
      category: 'Pains & Pâtes',
      barcode: '3760138012043',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Pauvre en sucre'],
      imageUrl: '',
      emoji: '🌿',
    ),
    
    AlternativeProduct(
      id: 12,
      name: 'jus de clémentines pressées',
      brand: 'Andros',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3045320104172',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/304/532/010/4172/front_fr.717.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 13,
      name: 'Avoine CacaoSans sucres ajoutés**Contient des sucres naturellement présents',
      brand: 'Auchan Bio',
      category: 'Produits laitiers',
      barcode: '3596710523023',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Sans lactose', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/359/671/052/3023/front_fr.31.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 14,
      name: 'Dessert 100% végétal au riz et au chocolat',
      brand: 'Grandeur Nature',
      category: 'Pains & Pâtes',
      barcode: '3252920038503',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Sans lactose', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/325/292/003/8503/front_fr.37.400.jpg',
      emoji: '🍫',
    ),
    
    AlternativeProduct(
      id: 16,
      name: 'Maïs',
      brand: 'Carrefour',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3560071511760',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: '',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 17,
      name: 'Chips\'O maïs nature',
      brand: 'Pural',
      category: 'Pains & Pâtes',
      barcode: '3184340004809',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/318/434/000/4809/front_fr.21.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 18,
      name: 'Maïs',
      brand: 'Carrefour, Carrefour Classic\'',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3560071006822',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/356/007/100/6822/front_fr.104.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 19,
      name: 'Couscous de maïs sans gluten, 375g',
      brand: 'U, U Sans Gluten',
      category: 'Pains & Pâtes',
      barcode: '3256229791459',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/325/622/979/1459/front_fr.3.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 20,
      name: 'Fleur De Maïs Maïsla',
      brand: 'Tipiak, Tipiak Restauration',
      category: 'Pains & Pâtes',
      barcode: '3165440003510',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/316/544/000/3510/front_fr.15.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 21,
      name: 'Couscous semoule de maïs',
      brand: 'Monoprix',
      category: 'Pains & Pâtes',
      barcode: '3350033289253',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/335/003/328/9253/front_fr.20.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 22,
      name: 'Pruneaux sans sucres ajoutés',
      brand: 'Pruni',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3361291956016',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/336/129/195/6016/front_fr.23.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 23,
      name: 'Couscous Oriental Semoule Maïs Et Riz Bio Sans Gluten',
      brand: 'Léa Nature Jardin Bio',
      category: 'Pains & Pâtes',
      barcode: '3456300005820',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Sans lactose'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/345/630/000/5820/front_fr.27.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 24,
      name: 'Maïs croquant',
      brand: 'Auchan',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3596710484522',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/359/671/048/4522/front_fr.31.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 25,
      name: 'Blédi à boire multivitamines Oranges',
      brand: 'Blédina, Danone',
      category: 'Pains & Pâtes',
      barcode: '3041090070365',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/304/109/007/0365/front_fr.26.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 26,
      name: 'Petits Filous Aux Fruits Panachés 6,9 %',
      brand: 'Yoplait',
      category: 'Pains & Pâtes',
      barcode: '3176572516007',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Sans lactose', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/317/657/251/6007/front_fr.4.400.jpg',
      emoji: '🍎',
    ),
    
    AlternativeProduct(
      id: 28,
      name: 'Penne de maïs',
      brand: 'Moulin des Moines',
      category: 'Pains & Pâtes',
      barcode: '3347430388832',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/334/743/038/8832/front_fr.4.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 29,
      name: 'Jus de pamplemousse rose à base de concentréteneur en fruits 100%Riche en vitamine CSans sucres ajoutés** Comme tous les jus de fruits . Contient les sucres naturellement présents dans les fruits.',
      brand: 'Auchan',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3254560025899',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/325/456/002/5899/front_en.33.400.jpg',
      emoji: '🍎',
    ),
    AlternativeProduct(
      id: 30,
      name: 'Thé Vert au Jus de Citrons',
      brand: 'Herbalist, Herbalist Infusions Véritables',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3760214930117',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/376/021/493/0117/front_fr.29.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 31,
      name: 'TONUS* Orange, Raisin, Kiwi, Citron vert - 100% Pur Jus - Riche en Vitamine C.* La vitamine C contribue à réduire la fatigue',
      brand: 'Auchan',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3596710480111',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/359/671/048/0111/front_fr.18.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 32,
      name: 'Citron vert à diluer sans sucres ajoutés',
      brand: 'Pulco',
      category: 'Snacks & Petit-déjeuner',
      barcode: '5410221305382',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/541/022/130/5382/front_fr.32.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 33,
      name: 'Matin léger - Boisson au lait au chocolat',
      brand: 'Lactel',
      category: 'Produits laitiers',
      barcode: '3428273160035',
      availability: 'Supermarches',
      benefits: ['Sans lactose', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/342/827/316/0035/front_fr.4.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 34,
      name: 'Myrtille sans sucres ajoutés',
      brand: 'Lucien Georgelin',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3330720244031',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/333/072/024/4031/front_fr.27.400.jpg',
      emoji: '🍎',
    ),
    AlternativeProduct(
      id: 35,
      name: 'fruits des bois à la vanille',
      brand: 'Karine & Jeff, Le bonheur est dans le pot',
      category: 'Pains & Pâtes',
      barcode: '3760052230660',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/376/005/223/0660/front_fr.45.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 36,
      name: 'Nectar orange/pêche/abricot sans sucres ajoutés brique 1L',
      brand: 'U',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3256224761129',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/325/622/476/1129/front_fr.57.400.jpg',
      emoji: '🍎',
    ),
    AlternativeProduct(
      id: 37,
      name: 'Confiture orange sans sucre ajouté',
      brand: 'Smucker\'s',
      category: 'Snacks & Petit-déjeuner',
      barcode: '0051500040164',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/005/150/004/0164/front_fr.4.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 38,
      name: '1.2.3 fruits jus d\'orange',
      brand: '1 2 3 Fruits',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3660668001978',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/366/066/800/1978/front_fr.26.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 39,
      name: 'Compote de pêches jaunes avec morceaux',
      brand: 'Coteaux nantais',
      category: 'Pains & Pâtes',
      barcode: '3301594000252',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/330/159/400/0252/front_fr.46.400.jpg',
      emoji: '🍎',
    ),
    AlternativeProduct(
      id: 40,
      name: 'Jus de pêche biologique',
      brand: 'Delizum',
      category: 'Pains & Pâtes',
      barcode: '8436029241544',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Sans lactose'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/843/602/924/1544/front_fr.4.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 41,
      name: 'Pennes pois chiches et maïs',
      brand: 'Markal',
      category: 'Pains & Pâtes',
      barcode: '3329489422507',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/332/948/942/2507/front_en.7.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 42,
      name: 'Ananas en morceaux au jus d\'ananas, certifié AB',
      brand: 'Monoprix bio',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3350031899461',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/335/003/189/9461/front_fr.16.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 43,
      name: 'Ananas tranches brisées jus naturel',
      brand: 'Marque Repère, Fruistar',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3564700006948',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/356/470/000/6948/front_fr.8.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 44,
      name: 'Jus d\'Ananas à base de concentré',
      brand: 'U',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3256223028353',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/325/622/302/8353/front_fr.23.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 45,
      name: 'Riz calcium naturéo',
      brand: 'NATURÉ O',
      category: 'Pains & Pâtes',
      barcode: '3701091716432',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Sans lactose', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/370/109/171/6432/front_fr.42.400.jpg',
      emoji: '🌿',
    ),
    
    AlternativeProduct(
      id: 47,
      name: 'Légumes, riz et poulet',
      brand: 'Alnatura',
      category: 'Pains & Pâtes',
      barcode: '4104420146846',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/410/442/014/6846/front_fr.6.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 48,
      name: 'Krupky - Soufflé de Maïs Bébé',
      brand: 'Krupky, Rej',
      category: 'Pains & Pâtes',
      barcode: '8594038913668',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/859/403/891/3668/front_fr.29.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 49,
      name: 'Riz soufflé',
      brand: 'Grillon d\'Or',
      category: 'Snacks & Petit-déjeuner',
      barcode: '8471557500763',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/847/155/750/0763/front_fr.11.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 50,
      name: 'Jus de Pruneau issu de l\'agriculture biologique*Sans sucres ajoutés (dans la déno commerciale)* Comme tous les jus de fruits. Contient les sucres naturellement présents dans les fruits.',
      brand: 'Auchan Bio',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3596710473090',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/359/671/047/3090/front_fr.147.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 51,
      name: 'Tagliatelles Thaïes de Riz Complet',
      brand: 'Autour du riz',
      category: 'Pains & Pâtes',
      barcode: '3760103146704',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/376/010/314/6704/front_fr.20.400.jpg',
      emoji: '🌾',
    ),
    AlternativeProduct(
      id: 52,
      name: 'Boisson épeautre',
      brand: 'Bjorg',
      category: 'Produits laitiers',
      barcode: '3229820798493',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Sans lactose', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/322/982/079/8493/front_fr.5.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 53,
      name: 'Concentré citron A utiliser pour vos assaisonnements',
      brand: 'Casino',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3222471021538',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/322/247/102/1538/front_fr.10.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 54,
      name: 'Herbalist Bio Thé Vert Au Jus de Grenade',
      brand: 'Herbalist, Herbalist Infusions Véritables',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3760214930100',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/376/021/493/0100/front_fr.22.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 55,
      name: 'Riz au lait de coco vegetal 2x125g',
      brand: 'La Coconut Collab, La Coop, The Coconut Co.',
      category: 'Pains & Pâtes',
      barcode: '5060426810107',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Sans lactose', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/506/042/681/0107/front_fr.53.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 56,
      name: 'Maïs SSA 1/4 x3',
      brand: 'Bonduelle',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3083681127430',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/308/368/112/7430/front_fr.50.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 57,
      name: 'Recette N° 17 - Chocolat au Lait de coco - Coco rapée',
      brand: 'Carré Suisse',
      category: 'Pains & Pâtes',
      barcode: '3760231780771',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Sans lactose', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/376/023/178/0771/front_en.31.400.jpg',
      emoji: '🍫',
    ),
    AlternativeProduct(
      id: 58,
      name: 'Specialité concentrée au citron',
      brand: 'Moulin de Valdonne',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3272036007583',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/327/203/600/7583/front_fr.4.400.jpg',
      emoji: '🥤',
    ),
    AlternativeProduct(
      id: 59,
      name: 'Boulgour de riz à la châtaigne',
      brand: 'celnat, les natures',
      category: 'Pains & Pâtes',
      barcode: '3273120019482',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/327/312/001/9482/front_fr.16.400.jpg',
      emoji: '🌾',
    ),
    AlternativeProduct(
      id: 60,
      name: 'Céréchoc farine de maïs et de riz',
      brand: 'Gerblé, Gerblé sans gluten',
      category: 'Pains & Pâtes',
      barcode: '3175681054332',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/317/568/105/4332/front_fr.14.400.jpg',
      emoji: '🌾',
    ),
    
    AlternativeProduct(
      id: 62,
      name: 'Tortillas de maïs',
      brand: 'Tortillas Guanajuato',
      category: 'Pains & Pâtes',
      barcode: '7503008588288',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/750/300/858/8288/front_fr.3.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 63,
      name: 'Pur jus de raison muscaté',
      brand: 'Plein Fruit',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3274936601205',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/327/493/660/1205/front_fr.16.400.jpg',
      emoji: '🍎',
    ),
    AlternativeProduct(
      id: 64,
      name: 'Boisson végétale à base de riz',
      brand: 'Casino, Casino Bio',
      category: 'Produits laitiers',
      barcode: '3222475419102',
      availability: 'Supermarches',
      benefits: ['Sans lactose', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/322/247/541/9102/front_fr.35.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 65,
      name: 'Jus mirabelle de Lorraine "fruits de chez nous"',
      brand: 'U',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3256224126539',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/325/622/412/6539/front_fr.44.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 66,
      name: 'Crème catalane - sans gluten',
      brand: 'Carmencita, Jesus Navarro',
      category: 'Pains & Pâtes',
      barcode: '8413700405815',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Sans lactose'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/841/370/040/5815/front_fr.34.400.jpg',
      emoji: '🥛',
    ),
    AlternativeProduct(
      id: 67,
      name: 'Purée de tomates, issu de l\'agriculture biologqiue, prête à consommer',
      brand: 'Grandeur Nature',
      category: 'Pains & Pâtes',
      barcode: '3252920048533',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/325/292/004/8533/front_fr.3.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 68,
      name: 'Pruneaux dénoyautés au jus de pruneaux',
      brand: 'Maitre Prunille Food Service',
      category: 'Snacks & Petit-déjeuner',
      barcode: '0035024901715',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/003/502/490/1715/front_fr.11.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 69,
      name: 'Purée nutritionnelle à la patate douce, à la carotte et au poivre timut',
      brand: 'BAOUW!',
      category: 'Pains & Pâtes',
      barcode: '3760267400896',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/376/026/740/0896/front_fr.3.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 70,
      name: 'Sablé à la châtaigne - A base de farine de riz',
      brand: 'Esprit de fete,Esprit Biscuit',
      category: 'Pains & Pâtes',
      barcode: '3301310012378',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/330/131/001/2378/front_fr.12.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 71,
      name: 'Compote la pêche en morceaux',
      brand: 'Charles & Alice',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3297760092223',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/329/776/009/2223/front_fr.3.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 72,
      name: 'Maïs doux',
      brand: 'Auchan, Auchan Bio',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3596710479962',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/359/671/047/9962/front_fr.72.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 73,
      name: '100% végétal au riz dessert praliné',
      brand: 'Grandeur Nature, Laiterie le gall',
      category: 'Pains & Pâtes',
      barcode: '3252920038534',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Sans lactose', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/325/292/003/8534/front_fr.34.400.jpg',
      emoji: '🌾',
    ),
    
    AlternativeProduct(
      id: 75,
      name: 'Tagliatelles Thaïes de Riz Rouge',
      brand: 'Autour du Riz',
      category: 'Pains & Pâtes',
      barcode: '3760103146742',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/376/010/314/6742/front_fr.23.400.jpg',
      emoji: '🌾',
    ),
    AlternativeProduct(
      id: 76,
      name: 'Maïs bio sans sucres ajoutés',
      brand: 'Bio Village, Marque Repère',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3564707093002',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/356/470/709/3002/front_fr.24.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 77,
      name: 'Boisson bio au riz et à la noix de coco',
      brand: 'Sojasun',
      category: 'Produits laitiers',
      barcode: '3273220076828',
      availability: 'Supermarches',
      benefits: ['Sans lactose', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/327/322/007/6828/front_fr.16.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 78,
      name: 'Tartine craquante sarrasin riz maïs',
      brand: 'Biocoop',
      category: 'Pains & Pâtes',
      barcode: '3760121212870',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/376/012/121/2870/front_fr.54.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 79,
      name: 'Bramata Semoule de maïs gros grains',
      brand: 'Migros, Terrasuisse',
      category: 'Pains & Pâtes',
      barcode: '7613269317173',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/761/326/931/7173/front_fr.14.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 80,
      name: 'Amidon de maïs bio',
      brand: 'Bioculinair, Joannusmolen',
      category: 'Pains & Pâtes',
      barcode: '8713445020282',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/871/344/502/0282/front_fr.45.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 81,
      name: 'Galettes de maïs sans gluten sans sucres',
      brand: 'Gerblé',
      category: 'Pains & Pâtes',
      barcode: '3175681054363',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/317/568/105/4363/front_fr.9.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 82,
      name: 'Crème de noix de coco',
      brand: 'Aroy-D Thai Agri Food Public Company Limited',
      category: 'Pains & Pâtes',
      barcode: '0016229909819',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/001/622/990/9819/front_en.11.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 83,
      name: 'Spaghetti farines de maïs et de riz',
      brand: 'Gerblé',
      category: 'Pains & Pâtes',
      barcode: '3175681054486',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/317/568/105/4486/front_fr.9.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 84,
      name: 'Cocktail de fruits - orange ananas citron vert - 100% pur jus - naturellement riche en vitamine C',
      brand: 'Auchan',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3596710408504',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/359/671/040/8504/front_fr.30.400.jpg',
      emoji: '🍎',
    ),
    AlternativeProduct(
      id: 85,
      name: 'Nectar orange pêche abricot ss sucre ajoutés brique de 1 litre',
      brand: 'U, U Bio',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3256228434005',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/325/622/843/4005/front_fr.16.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 86,
      name: 'Jus d\'ananas à base de concentré.',
      brand: 'Plein Fruit',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3274936041315',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/327/493/604/1315/front_fr.4.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 87,
      name: 'Nectar, Orange, Pêche, Abricot sans sucres ajoutés',
      brand: 'U',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3256224761167',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/325/622/476/1167/front_fr.32.400.jpg',
      emoji: '🍎',
    ),
    AlternativeProduct(
      id: 88,
      name: 'Jus d\'ananas à base de concentré',
      brand: 'Auchan, Rik & Rok',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3596710404063',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/359/671/040/4063/front_fr.49.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 89,
      name: 'Jus d\'ananas à base de concentré',
      brand: 'Plein Fruit',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3274936601304',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/327/493/660/1304/front_fr.16.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 90,
      name: 'farine de riz',
      brand: 'Sans gluten pour tous',
      category: 'Pains & Pâtes',
      barcode: '76887017',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/000/007/688/7017/front_fr.4.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 91,
      name: 'Lait d\'amande Sans sucres ajoutés',
      brand: 'Bjorg',
      category: 'Produits laitiers',
      barcode: '3229820788487',
      availability: 'Supermarches',
      benefits: ['Sans lactose', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/322/982/078/8487/front_fr.4.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 92,
      name: 'NESQUIK Moins de Sucres Poudre Cacaotée',
      brand: 'Nestlé, Nesquik',
      category: 'Pains & Pâtes',
      barcode: '7613036352734',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/761/303/635/2734/front_fr.189.400.jpg',
      emoji: '🍫',
    ),
    AlternativeProduct(
      id: 93,
      name: 'Jus d\'orange avec pulpe à base de concentré doux',
      brand: 'Minute maid',
      category: 'Snacks & Petit-déjeuner',
      barcode: '5449000034274',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/544/900/003/4274/front_fr.5.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 94,
      name: 'Boisson avoine sans sucres ajoutés',
      brand: 'Bjorg,Carrefour Bio',
      category: 'Produits laitiers',
      barcode: '3229820799346',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Sans lactose', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/322/982/079/9346/front_fr.31.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 95,
      name: 'Tartines craquantes bio au maïs',
      brand: 'Le pain des fleurs',
      category: 'Pains & Pâtes',
      barcode: '3380380077296',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/338/038/007/7296/front_fr.62.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 96,
      name: '100% Pur Jus Clémentines pressées',
      brand: 'Andros',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3608580913856',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/360/858/091/3856/front_fr.39.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 97,
      name: 'Maïs doux',
      brand: 'Carrefour',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3560071213411',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: '',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 98,
      name: 'Maïs en grains',
      brand: 'Auchan, Auchan Bio',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3596710457472',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/359/671/045/7472/front_fr.48.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 99,
      name: 'Jus 100% pruneau',
      brand: 'Coeur de Pom',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3760195901274',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/376/019/590/1274/front_fr.4.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 100,
      name: 'Chocolat en poudre grand arôme',
      brand: 'Poulain',
      category: 'Pains & Pâtes',
      barcode: '4622060288912',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/462/206/028/8912/front_fr.4.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 101,
      name: 'Maïs sans sucres ajoutés',
      brand: 'Bonduelle',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3083680017763',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/308/368/001/7763/front_fr.4.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 102,
      name: 'Gourmand et végétal au lait de coco',
      brand: 'Andros',
      category: 'Produits laitiers',
      barcode: '3608580891017',
      availability: 'Supermarches',
      benefits: ['Sans lactose', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/360/858/089/1017/front_fr.4.400.jpg',
      emoji: '🍫',
    ),
    AlternativeProduct(
      id: 103,
      name: 'Cacao en poudre 1% M.G et 1% sucres',
      brand: 'Dukan',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3760151013812',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Sans lactose', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/376/015/101/3812/front_fr.34.400.jpg',
      emoji: '🍫',
    ),
    AlternativeProduct(
      id: 104,
      name: 'Crème de vinaigre au vinaigre Balsamique',
      brand: 'Martin Pouret',
      category: 'Pains & Pâtes',
      barcode: '3165350915026',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/316/535/091/5026/front_fr.20.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 105,
      name: 'Epicerie / Epicerie Sucrée / Compotes Et Purées De Fruits',
      brand: 'Coteaux nantais',
      category: 'Snacks & Petit-déjeuner',
      barcode: '3301597002383',
      availability: 'Supermarches',
      benefits: ['Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/330/159/700/2383/front_fr.19.400.jpg',
      emoji: '🍎',
    ),
    AlternativeProduct(
      id: 106,
      name: 'Riz Thaï',
      brand: 'Uncle Ben\'s',
      category: 'Pains & Pâtes',
      barcode: '5410673731036',
      availability: 'Supermarches',
      benefits: ['Sans gluten'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/541/067/373/1036/front_fr.8.400.jpg',
      emoji: '🌿',
    ),
    AlternativeProduct(
      id: 107,
      name: 'grand arôme 32% cacao sélectionné',
      brand: 'Mondelez, Poulain',
      category: 'Pains & Pâtes',
      barcode: '3538280031515',
      availability: 'Supermarches',
      benefits: ['Sans gluten', 'Pauvre en sucre'],
      imageUrl: 'https://images.openfoodfacts.org/images/products/353/828/003/1515/front_fr.46.400.jpg',
      emoji: '🌿',
    ),
  ];

  static List<AlternativeProduct> getAllProducts() {
    return products;
  }

  static List<AlternativeProduct> getProductsByCategory(String category) {
    return products.where((p) => p.category == category).toList();
  }

  static List<AlternativeProduct> searchProducts(String query) {
    final lowerQuery = query.toLowerCase();
    return products.where((p) =>
      p.name.toLowerCase().contains(lowerQuery) ||
      p.brand.toLowerCase().contains(lowerQuery) ||
      p.category.toLowerCase().contains(lowerQuery)
    ).toList();
  }

  static List<String> getCategories() {
    return products.map((p) => p.category).toSet().toList()..sort();
  }
}
